build turnkey:
  stage: build
  image: docker:stable
  only:
    refs: ["release/**"]
  services: ["docker:dind"]
  script: |
    sed -i "s/gitlab-ce:latest/gitlab-ce:$TAG/" Dockerfile
    cat Dockerfile
    docker build --tag "$CI_REGISTRY_IMAGE:$TAG" .
    echo "$CI_REGISTRY_PASSWORD" | docker login --username="$CI_REGISTRY_USER" --password-stdin
    docker push "$CI_REGISTRY_IMAGE:$TAG"
