build turnkey:
  image: docker:latest
  stage: build
  only:
    refs: [ "master" ]
    changes:
      - assets/**/*
      - .gitlab-ci.yml
      - Dockerfile
  services:
    - docker:dind
  parallel:
    matrix:
      # define the gitlab versions to build
      - TAG:
        - "latest"
        - "gitlab-ce:12.7.0-ce.0"
  script:
    - sed -i "s/gitlab-ce:latest/gitlab-ce:$TAG/" /Dockerfile
    - docker build --quiet --tag "$CI_REGISTRY_IMAGE:$TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$TAG"
