build turnkey:
  image: docker:latest
  stage: build
  only:
    refs: [ "master" ]
    changes:
      - assets/**/*
      - .gitlab-ci.yml
      - Dockerfile
  services: [ "docker:dind" ]
  parallel:
    matrix:
      # define the Gitlab versions to build
      - TAG:
        - "latest"
        - "12.7.0-ce.0"
  script:
    - sed -i "s/gitlab-ce:latest/gitlab-ce:$TAG/" Dockerfile
    - cat Dockerfile
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" --username="$CI_REGISTRY_USER" --password-stdin
    - docker build --tag "$CI_REGISTRY_IMAGE:$TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$TAG"
