# original source: https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml
version: '3.5'

# please research https://docs.docker.com/compose/environment-variables/ for howto setup your environment
services:
  gitlab:
    container_name: gitlab
    restart: always
    image: registry.gitlab.com/systemkern/gitlab-aio:latest
    ports:
      - "81:80"
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-etc:/etc/gitlab:Z
      - gitlab-log:/var/log/gitlab:Z
      - gitlab-opt:/var/opt/gitlab:Z
    environment:
      - TZ=Austria/Vienna
      - GITLAB_TIMEZONE=Vienna
      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_SSH_PORT=10022
      - GITLAB_RELATIVE_URL_ROOT=

      - GITLAB_ROOT_PASSWORD=password
      - GITLAB_ROOT_EMAIL=

      - GITLAB_SECRETS_SECRET_KEY_BASE=secret11111111112222222222333333333344444444445555555555666666666612345
      - GITLAB_SECRETS_OTP_KEY_BASE=secret11111111112222222222333333333344444444445555555555666666666612345
      - GITLAB_SECRETS_DB_KEY_BASE=secret11111111112222222222333333333344444444445555555555666666666612345

volumes:
  gitlab-etc:
  gitlab-log:
  gitlab-opt:
