#!/bin/bash
########################################
set -o pipefail
set -e # exit on immediately on every error
set -u # error on usage of undefined variables
########################################
echo "GITLAB_ROOT_URL: $GITLAB_ROOT_URL"

export GITLAB_PROTOCOL="$(echo "$GITLAB_ROOT_URL" | grep :// | sed -e's,^\(.*://\).*,\1,g')"
export GITLAB_NOPROTO_URL="$(echo ${GITLAB_ROOT_URL/"$GITLAB_PROTOCOL"/})"
export RM_USER="$(echo "$GITLAB_NOPROTO_URL" | grep @ | cut -d@ -f1)"
export GITLAB_HOSTPORT="$(echo ${GITLAB_NOPROTO_URL/"$RM_USER"@/} | cut -d/ -f1)"
export GITLAB_HOST="$(echo "$GITLAB_HOSTPORT" | sed -e 's,:.*,,g')"
export GITLAB_PORT="$(echo "$GITLAB_HOSTPORT" | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"

echo "GITLAB_PROTOCOL:$GITLAB_PROTOCOL"
echo "GITLAB_HOST:$GITLAB_HOST"
echo "GITLAB_PORT:$GITLAB_PORT"

### Gitlab dynamic variables created from ENV mentioned in Dockerfile
export DOCKER_REGISTRY_PORT=${DOCKER_REGISTRY_PORT:-5050}
export GITLAB_ROOT_URL=${GITLAB_ROOT_URL:-"http://$GITLAB_HOSTPORT"}
export DOCKER_REGISTRY="$GITLAB_HOST:${DOCKER_REGISTRY_PORT}"
export DOCKER_REGISTRY_EXTERNAL_URL="http://${DOCKER_REGISTRY}"

export GITLAB_OMNIBUS_CONFIG="\
    external_url '$GITLAB_ROOT_URL';                                \
    nginx['redirect_http_to_https'] = false;                        \
    registry_external_url '$DOCKER_REGISTRY_EXTERNAL_URL';          \
    registry_nginx['enable'] = true;                                \
    registry_nginx['listen_port'] = $DOCKER_REGISTRY_PORT;          \
    redis['bind'] = '127.0.0.1';                                    \
    redis['port'] = 6379;                                           \
    "

echo "##########################################"
echo "$GITLAB_OMNIBUS_CONFIG"
echo "##########################################"

# Gitlab's Omnibus wrapper uses undefined variables
set +u
